//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFMediaPlayer.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CFMediaPlayer.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [All artists].
        /// </summary>
        internal static string AllArtistsText {
            get {
                return ResourceManager.GetString("AllArtistsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [All albums].
        /// </summary>
        internal static string AllMediaItemCollectionsText {
            get {
                return ResourceManager.GetString("AllMediaItemCollectionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [All media items].
        /// </summary>
        internal static string AllMediaItemsText {
            get {
                return ResourceManager.GetString("AllMediaItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [All media locations].
        /// </summary>
        internal static string AllMediaLocationsText {
            get {
                return ResourceManager.GetString("AllMediaLocationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [All].
        /// </summary>
        internal static string AllText {
            get {
                return ResourceManager.GetString("AllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Preset Settings.
        /// </summary>
        internal static string CustomAudioPresetSettings {
            get {
                return ResourceManager.GetString("CustomAudioPresetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to playlist.
        /// </summary>
        internal static string MainAddMediaItemToPlaylistText {
            get {
                return ResourceManager.GetString("MainAddMediaItemToPlaylistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select action.
        /// </summary>
        internal static string MainSelectActionText {
            get {
                return ResourceManager.GetString("MainSelectActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an album.
        /// </summary>
        internal static string MainSelectAlbumText {
            get {
                return ResourceManager.GetString("MainSelectAlbumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an artist.
        /// </summary>
        internal static string MainSelectArtistText {
            get {
                return ResourceManager.GetString("MainSelectArtistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a media item.
        /// </summary>
        internal static string MainSelectMediaItemText {
            get {
                return ResourceManager.GetString("MainSelectMediaItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select media location.
        /// </summary>
        internal static string MainSelectMediaLocationText {
            get {
                return ResourceManager.GetString("MainSelectMediaLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select play mode.
        /// </summary>
        internal static string MainSelectPlayModeText {
            get {
                return ResourceManager.GetString("MainSelectPlayModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select play order.
        /// </summary>
        internal static string MainSelectPlayOrderText {
            get {
                return ResourceManager.GetString("MainSelectPlayOrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from {0}.
        /// </summary>
        internal static string MediaItemActionRemoveFromPlaylist {
            get {
                return ResourceManager.GetString("MediaItemActionRemoveFromPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from queue.
        /// </summary>
        internal static string MediaItemActionRemoveFromQueue {
            get {
                return ResourceManager.GetString("MediaItemActionRemoveFromQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} random music items.
        /// </summary>
        internal static string MediaItemActionsAddRandomItemsToQueue {
            get {
                return ResourceManager.GetString("MediaItemActionsAddRandomItemsToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to {0}.
        /// </summary>
        internal static string MediaItemActionsAddToPlaylist {
            get {
                return ResourceManager.GetString("MediaItemActionsAddToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to queue (End).
        /// </summary>
        internal static string MediaItemActionsAddToQueueEnd {
            get {
                return ResourceManager.GetString("MediaItemActionsAddToQueueEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear queue.
        /// </summary>
        internal static string MediaItemActionsClearQueue {
            get {
                return ResourceManager.GetString("MediaItemActionsClearQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to {0}.
        /// </summary>
        internal static string MediaItemActionsOpenMediaItemCollection {
            get {
                return ResourceManager.GetString("MediaItemActionsOpenMediaItemCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media location.
        /// </summary>
        internal static string MediaLocation {
            get {
                return ResourceManager.GetString("MediaLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audiobooks.
        /// </summary>
        internal static string MediaSourceAudiobooksText {
            get {
                return ResourceManager.GetString("MediaSourceAudiobooksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google cloud.
        /// </summary>
        internal static string MediaSourceGoogleText {
            get {
                return ResourceManager.GetString("MediaSourceGoogleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string MediaSourceInternalStorageText {
            get {
                return ResourceManager.GetString("MediaSourceInternalStorageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string MediaSourceMusicText {
            get {
                return ResourceManager.GetString("MediaSourceMusicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneDrive.
        /// </summary>
        internal static string MediaSourceOneDriveText {
            get {
                return ResourceManager.GetString("MediaSourceOneDriveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        internal static string MediaSourcePlaylistsText {
            get {
                return ResourceManager.GetString("MediaSourcePlaylistsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcasts.
        /// </summary>
        internal static string MediaSourcePodcastsText {
            get {
                return ResourceManager.GetString("MediaSourcePodcastsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        internal static string MediaSourceQueueText {
            get {
                return ResourceManager.GetString("MediaSourceQueueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio streams.
        /// </summary>
        internal static string MediaSourceRadioStreamsText {
            get {
                return ResourceManager.GetString("MediaSourceRadioStreamsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New playlist.
        /// </summary>
        internal static string NewPlaylist {
            get {
                return ResourceManager.GetString("NewPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist name.
        /// </summary>
        internal static string NewPlaylistPlaylistNameLabel {
            get {
                return ResourceManager.GetString("NewPlaylistPlaylistNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [New Playlist].
        /// </summary>
        internal static string NewPlaylistText {
            get {
                return ResourceManager.GetString("NewPlaylistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [None].
        /// </summary>
        internal static string NoneText {
            get {
                return ResourceManager.GetString("NoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        internal static string Playlist {
            get {
                return ResourceManager.GetString("Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search {0}....
        /// </summary>
        internal static string SearchWithParam {
            get {
                return ResourceManager.GetString("SearchWithParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select audio settings.
        /// </summary>
        internal static string SelectAudioSettingsText {
            get {
                return ResourceManager.GetString("SelectAudioSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Audio Preset.
        /// </summary>
        internal static string SelectedAudioPreset {
            get {
                return ResourceManager.GetString("SelectedAudioPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        internal static string SelectLanguageText {
            get {
                return ResourceManager.GetString("SelectLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select playlist.
        /// </summary>
        internal static string SelectPlaylistText {
            get {
                return ResourceManager.GetString("SelectPlaylistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select theme.
        /// </summary>
        internal static string SelectThemeText {
            get {
                return ResourceManager.GetString("SelectThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Shuffle].
        /// </summary>
        internal static string ShuffleText {
            get {
                return ResourceManager.GetString("ShuffleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        internal static string StorageLocationExternal {
            get {
                return ResourceManager.GetString("StorageLocationExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        internal static string StorageLocationInternal {
            get {
                return ResourceManager.GetString("StorageLocationInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string TabCurrentText {
            get {
                return ResourceManager.GetString("TabCurrentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string TabLibraryText {
            get {
                return ResourceManager.GetString("TabLibraryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        internal static string TabManagePlaylistsText {
            get {
                return ResourceManager.GetString("TabManagePlaylistsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string TabSearchText {
            get {
                return ResourceManager.GetString("TabSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string TabSettingsText {
            get {
                return ResourceManager.GetString("TabSettingsText", resourceCulture);
            }
        }
    }
}
