//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFMediaPlayer.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CFMediaPlayer.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to playlist.
        /// </summary>
        internal static string MainAddMediaItemToPlaylistText {
            get {
                return ResourceManager.GetString("MainAddMediaItemToPlaylistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select action.
        /// </summary>
        internal static string MainSelectActionText {
            get {
                return ResourceManager.GetString("MainSelectActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an album.
        /// </summary>
        internal static string MainSelectAlbumText {
            get {
                return ResourceManager.GetString("MainSelectAlbumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an artist.
        /// </summary>
        internal static string MainSelectArtistText {
            get {
                return ResourceManager.GetString("MainSelectArtistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a media item.
        /// </summary>
        internal static string MainSelectMediaItemText {
            get {
                return ResourceManager.GetString("MainSelectMediaItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select media location.
        /// </summary>
        internal static string MainSelectMediaLocationText {
            get {
                return ResourceManager.GetString("MainSelectMediaLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select play mode.
        /// </summary>
        internal static string MainSelectPlayModeText {
            get {
                return ResourceManager.GetString("MainSelectPlayModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from playlist {0}.
        /// </summary>
        internal static string MediaItemActionRemoveFromPlaylist {
            get {
                return ResourceManager.GetString("MediaItemActionRemoveFromPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from queue.
        /// </summary>
        internal static string MediaItemActionRemoveFromQueue {
            get {
                return ResourceManager.GetString("MediaItemActionRemoveFromQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to playlist {0}.
        /// </summary>
        internal static string MediaItemActionsAddToPlaylist {
            get {
                return ResourceManager.GetString("MediaItemActionsAddToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to queue (End).
        /// </summary>
        internal static string MediaItemActionsAddToQueueEnd {
            get {
                return ResourceManager.GetString("MediaItemActionsAddToQueueEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to queue (Next).
        /// </summary>
        internal static string MediaItemActionsAddToQueueNext {
            get {
                return ResourceManager.GetString("MediaItemActionsAddToQueueNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear queue.
        /// </summary>
        internal static string MediaItemActionsClearQueue {
            get {
                return ResourceManager.GetString("MediaItemActionsClearQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential play.
        /// </summary>
        internal static string MediaPlayModesSequential {
            get {
                return ResourceManager.GetString("MediaPlayModesSequential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle (Artist).
        /// </summary>
        internal static string MediaPlayModesShuffleArtist {
            get {
                return ResourceManager.GetString("MediaPlayModesShuffleArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle (Album).
        /// </summary>
        internal static string MediaPlayModesShuffleMediaItemCollection {
            get {
                return ResourceManager.GetString("MediaPlayModesShuffleMediaItemCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle (Storage).
        /// </summary>
        internal static string MediaPlayModesShuffleStorage {
            get {
                return ResourceManager.GetString("MediaPlayModesShuffleStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single play.
        /// </summary>
        internal static string MediaPlayModesSingleMediaItem {
            get {
                return ResourceManager.GetString("MediaPlayModesSingleMediaItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google cloud.
        /// </summary>
        internal static string MediaSourceGoogleText {
            get {
                return ResourceManager.GetString("MediaSourceGoogleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal storage.
        /// </summary>
        internal static string MediaSourceInternalStorageText {
            get {
                return ResourceManager.GetString("MediaSourceInternalStorageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneDrive.
        /// </summary>
        internal static string MediaSourceOneDriveText {
            get {
                return ResourceManager.GetString("MediaSourceOneDriveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        internal static string MediaSourcePlaylistsText {
            get {
                return ResourceManager.GetString("MediaSourcePlaylistsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        internal static string MediaSourceQueueText {
            get {
                return ResourceManager.GetString("MediaSourceQueueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD card.
        /// </summary>
        internal static string MediaSourceSDCardText {
            get {
                return ResourceManager.GetString("MediaSourceSDCardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist name.
        /// </summary>
        internal static string NewPlaylistPlaylistNameLabel {
            get {
                return ResourceManager.GetString("NewPlaylistPlaylistNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [New Playlist].
        /// </summary>
        internal static string NewPlaylistText {
            get {
                return ResourceManager.GetString("NewPlaylistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select audio settings.
        /// </summary>
        internal static string SelectAudioSettingsText {
            get {
                return ResourceManager.GetString("SelectAudioSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select theme.
        /// </summary>
        internal static string SelectThemeText {
            get {
                return ResourceManager.GetString("SelectThemeText", resourceCulture);
            }
        }
    }
}
